language: r
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  - mkdir ~/bin
  - wget -P ~/bin/ https://www.dropbox.com/s/csi77fa994g9cpw/msms.jar?dl=1
  - wget -P ~/bin/ https://www.dropbox.com/s/m9ppejh6qz0eqmy/OmegaPlus?dl=1
  - wget -P ~/bin/ https://www.dropbox.com/s/el8375o09snd5v5/seq-gen?dl=1
  - chmod +x ~/bin/*

r_packages:
  - lintr
  - covr

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "library(covr); coveralls()"

notifications:
  email: false

