language: r
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  - mkdir -p ~/bin
  - wget -O ~/bin/msms.jar "$MSMS_URL"
  - wget -O ~/bin/OmegaPlus "$OMEGA_PLUS_URL"
  - wget -O ~/bin/seq-gen "$SEQGEN_URL"
  - chmod +x ~/bin/*

r_packages:
  - lintr
  - covr

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "library(covr); coveralls()"
