language: r
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  - mkdir ~/bin
  - wget -P ~/bin/ https://dl.dropboxusercontent.com/u/24814716/msms.jar
  - wget -P ~/bin/ https://dl.dropboxusercontent.com/u/24814716/OmegaPlus
  - wget -P ~/bin/ https://dl.dropboxusercontent.com/u/24814716/seq-gen
  - chmod +x ~/bin/*

r_packages:
  - lintr
  - covr

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "library(covr); coveralls()"

notifications:
  email: false

